from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Profile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("language", models.CharField(choices=[("uz", "Uzbek"), ("ru", "Russian"), ("en", "English")], default="en", max_length=2)), ("field", models.CharField(blank=True, max_length=80)), ("specialization", models.CharField(blank=True, max_length=80)), ("skills", models.JSONField(blank=True, default=list)), ("experience_level", models.CharField(blank=True, choices=[("none", "No experience"), ("junior", "Junior"), ("middle", "Middle"), ("senior", "Senior")], max_length=30)), ("work_format", models.CharField(choices=[("online", "Remote"), ("offline", "Office"), ("hybrid", "Hybrid"), ("any", "Any")], default="any", max_length=20)), ("location", models.CharField(blank=True, max_length=120)), ("experience", models.TextField(blank=True)), ("cv_generations", models.PositiveIntegerField(default=0)), ("updated_at", models.DateTimeField(auto_now=True)), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Vacancy", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("url", models.URLField(unique=True)), ("title", models.CharField(max_length=240)), ("text", models.TextField()), ("date", models.CharField(blank=True, max_length=80)), ("channel", models.CharField(blank=True, max_length=120)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="SavedJob", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_jobs", to=settings.AUTH_USER_MODEL)), ("vacancy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_by", to="jobs.vacancy"))]),
        migrations.CreateModel(name="ViewedJob", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("viewed_at", models.DateTimeField(auto_now=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="viewed_jobs", to=settings.AUTH_USER_MODEL)), ("vacancy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="views", to="jobs.vacancy"))]),
        migrations.CreateModel(name="VacancyAnalysis", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("result", models.JSONField(default=dict)), ("created_at", models.DateTimeField(auto_now=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ("vacancy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobs.vacancy"))]),
        migrations.AddConstraint(model_name="savedjob", constraint=models.UniqueConstraint(fields=("user", "vacancy"), name="unique_saved_job")),
        migrations.AddConstraint(model_name="viewedjob", constraint=models.UniqueConstraint(fields=("user", "vacancy"), name="unique_viewed_job")),
    ]
