# Generated by Django 5.2.17 on 2026-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_viewedjob_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_template',
            field=models.CharField(default='modern', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('data', 'Data'), ('qa', 'Qa'), ('devops', 'Devops'), ('mobile', 'Mobile'), ('product', 'Product'), ('project', 'Project'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('content', 'Content'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.CharField(default='FindYourJob partner', max_length=160),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=30),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('no_experience', 'No Experience'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=30),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='Worldwide', max_length=120),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On Site')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('design', 'Design'), ('data', 'Data'), ('qa', 'Qa'), ('devops', 'Devops'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('product', 'Product'), ('other', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('remote', 'Remote'), ('worldwide', 'Worldwide'), ('other', 'Other')], max_length=120),
        ),
    ]
