# Generated by Django 5.2.17 on 2026-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profile_certifications_profile_cv_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
