# Generated by Django 5.2.17 on 2026-09-16 05:26

from django.db import migrations, models


def copy_real_urls(apps, schema_editor):
    Vacancy = apps.get_model("jobs", "Vacancy")
    for vacancy in Vacancy.objects.all():
        if vacancy.channel == "seed-data" or not vacancy.url:
            vacancy.is_demo = True if vacancy.channel == "seed-data" else vacancy.is_demo
            vacancy.url = None if vacancy.channel == "seed-data" else vacancy.url
            vacancy.save(update_fields=["is_demo", "url"])
            continue
        vacancy.source_url = vacancy.url
        vacancy.source = "Telegram" if "t.me/" in vacancy.url else ""
        vacancy.save(update_fields=["source_url", "source"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profile_cv_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(copy_real_urls, migrations.RunPython.noop),
    ]
